language: cpp

git:
  depth: 1

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data

branches:
  only:
    - master

compiler:
  - clang
  - gcc ## Uncomment when we are up to full c++11 standards.

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install clang-3.7
  - sudo apt-get install libace-dev
  - sudo apt-get install libncurses5-dev
  - sudo apt-get install build-essential autoconf libtool make cmake git-core patch wget links zip unzip unrar
  - sudo apt-get install openssl libssl-dev mysql-server mysql-client libmysqlclient15-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  
install:
  - mysql -uroot -e 'create database test_mysql;'
  - mkdir bin
  - cd bin
  - cmake ../ -DSCRIPTS=1 -DTOOLS=1 -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DSERVERS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - $CXX --version
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -ujadecore -pjadecore auth < sql/base/auth_database.sql
  - cat sql/updates/auth/*_auth.sql | mysql -ujadecore -pjadecore auth
  - mysql -ujadecore -pjadecore characters < sql/base/characters_database.sql
  - cat sql/updates/characters/*_characters.sql | mysql -ujadecore -pjadecore characters
  - mysql -ujadecore -pjadecore world < sql/base/dev/world_database.sql
  - cat sql/updates/world/*_world.sql | mysql -ujadecore -pjadecore world
  - mysql -uroot < sql/create/drop_mysql.sql
  - cd bin
  - make clean
  - make -j 8 -k && make install
  - cd check_install/bin
